### 데이터 불러오기

In [10]:
import pandas as pd 
data = pd.read_csv("[지하철_102_raw]_서울교통공사_역별시간대별혼잡도_20221231.csv")
days = pd.read_csv("요일별비율산출.csv")
mons = pd.read_csv("월별비율산출.csv")
data.head(1)

,연번,요일구분,호선,역번호,출발역,상하구분,5시30분,6시00분,6시30분,7시00분,...,20시00분,20시30분,21시00분,21시30분,22시00분,22시30분,23시00분,23시30분,00시00분,00시30분
0,1,평일,1,150,서울역,상선,7.3,18.1,18.1,30.9,...,15.6,17.1,17.7,14.9,13.7,17.2,10.4,8.8,8.8,1.2

In [13]:
time_columns = ["5시30분", "6시00분", "6시30분", "7시00분", "7시30분", "8시00분", "8시30분", "9시00분", "9시30분", "10시00분", "10시30분", "11시00분", "11시30분", "12시00분", "12시30분", "13시00분", "13시30분", "14시00분", "14시30분", "15시00분", "15시30분", "16시00분", "16시30분", "17시00분", "17시30분", "18시00분", "18시30분", "19시00분", "19시30분", "20시00분", "20시30분", "21시00분", "21시30분", "22시00분", "22시30분", "23시00분", "23시30분", "00시00분", "00시30분"]

# 시간대 컬럼 생성 및 값을 채워넣기
for time_column in time_columns:
    data["시간대"] = time_column
    data[time_column] = data[time_column]

# 결과 확인
data.head()

,연번,요일구분,호선,역번호,출발역,상하구분,5시30분,6시00분,6시30분,7시00분,...,20시30분,21시00분,21시30분,22시00분,22시30분,23시00분,23시30분,00시00분,00시30분,시간대
0,1,평일,1,150,서울역,상선,7.3,18.1,18.1,30.9,...,17.1,17.7,14.9,13.7,17.2,10.4,8.8,8.8,1.2,00시30분
1,2,평일,1,150,서울역,하선,11.5,11.0,13.2,21.4,...,36.1,35.0,29.4,39.2,26.1,17.1,11.8,8.5,0.0,00시30분
2,3,평일,1,151,시청,상선,6.6,15.4,14.7,25.0,...,20.7,21.8,17.5,18.5,18.4,14.9,11.5,7.0,2.8,00시30분
3,4,평일,1,151,시청,하선,9.0,9.1,14.6,20.0,...,32.4,31.1,28.5,30.2,22.2,15.4,10.1,6.5,0.8,00시30분
4,5,평일,1,152,종각,상선,6.3,14.4,10.7,17.6,...,25.2,29.7,22.6,26.1,24.0,19.7,14.6,9.6,4.2,00시30분