In [3]:
## https://data.seoul.go.kr/dataList/OA-21285/F/1/datasetView.do 서울 실시간 도시데이터
import requests

url= "http://openapi.seoul.go.kr:8088/69576567536c736f3133357542784147/xml/citydata/1/5/강남역"
req = requests.get(url)
print(req)

<Response [200]>

In [4]:
!pip install xmltodict

Requirement already satisfied: xmltodict in c:\users\user\desktop\tempproject\venv\lib\site-packages (0.13.0)

In [5]:
import xmltodict

In [6]:
import requests
import pandas as pd

data = xmltodict.parse(req.text)
# data

In [7]:
data1 = pd.DataFrame(data['SeoulRtd.citydata']['CITYDATA'])
data1.info()
# (data['SeoulRtd.citydata']['CITYDATA']
#                      ['LIVE_PPLTN_STTS']['ROAD_TRAFFIC_STTS']['PRK_STTS']['SUB_STTS']['BUS_STN_STTS']
#                     ['SBIKE_STTS']['WEATHER_STTS']['CHARGER_STTS']['EVENT_STTS'])

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, LIVE_PPLTN_STTS to CHARGER_STTS
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   AREA_NM            8 non-null      object
 1   AREA_CD            8 non-null      object
 2   LIVE_PPLTN_STTS    1 non-null      object
 3   ROAD_TRAFFIC_STTS  2 non-null      object
 4   PRK_STTS           0 non-null      object
 5   SUB_STTS           1 non-null      object
 6   BUS_STN_STTS       1 non-null      object
 7   ACDNT_CNTRL_STTS   0 non-null      object
 8   SBIKE_STTS         1 non-null      object
 9   WEATHER_STTS       1 non-null      object
 10  CHARGER_STTS       1 non-null      object
 11  EVENT_STTS         0 non-null      object
dtypes: object(12)
memory usage: 832.0+ bytes

In [8]:
data1

,AREA_NM,AREA_CD,LIVE_PPLTN_STTS,ROAD_TRAFFIC_STTS,PRK_STTS,SUB_STTS,BUS_STN_STTS,ACDNT_CNTRL_STTS,SBIKE_STTS,WEATHER_STTS,CHARGER_STTS,EVENT_STTS
LIVE_PPLTN_STTS,강남역,POI014,"{'AREA_CONGEST_LVL': '붐빔', 'AREA_CONGEST_MSG':...",NaN,None,NaN,NaN,None,NaN,NaN,NaN,None
AVG_ROAD_DATA,강남역,POI014,NaN,{'ROAD_MSG': '해당 장소로 이동·진입시 시간이 다소 소요될 수 있어요.'...,None,NaN,NaN,None,NaN,NaN,NaN,None
ROAD_TRAFFIC_STTS,강남역,POI014,NaN,"[{'LINK_ID': '1210004100', 'ROAD_NM': '경부고속도로'...",None,NaN,NaN,None,NaN,NaN,NaN,None
SUB_STTS,강남역,POI014,NaN,NaN,None,"[{'SUB_STN_NM': '강남', 'SUB_STN_LINE': '2', 'SU...",NaN,None,NaN,NaN,NaN,None
BUS_STN_STTS,강남역,POI014,NaN,NaN,None,NaN,"[{'BUS_STN_ID': '121000009', 'BUS_ARS_ID': '22...",None,NaN,NaN,NaN,None
SBIKE_STTS,강남역,POI014,NaN,NaN,None,NaN,NaN,None,[{'SBIKE_SPOT_NM': '2407. 역삼.서초.삼성 세무서 앞 (역삼빌딩...,NaN,NaN,None
WEATHER_STTS,강남역,POI014,NaN,NaN,None,NaN,NaN,None,NaN,"{'WEATHER_TIME': '2023-08-24 14:51', 'TEMP': '...",NaN,None
CHARGER_STTS,강남역,POI014,NaN,NaN,None,NaN,NaN,None,NaN,NaN,"[{'STAT_NM': '역삼문화공원 지하3층주차장', 'STAT_ID': 'CV0...",None

## 데이터 추출

In [10]:
import requests
import xmltodict
import pandas as pd

url = "http://openapi.seoul.go.kr:8088/69576567536c736f3133357542784147/xml/citydata/1/5/POI001"
response = requests.get(url)

if response.status_code == 200:
    data = xmltodict.parse(response.text)
    
    # 실제 데이터가 있는 키 확인 및 사용
    city_data = data['SeoulRtd.citydata']['CITYDATA']['LIVE_PPLTN_STTS']['LIVE_PPLTN_STTS']
    
    # DataFrame 생성을 위한 딕셔너리 초기화
    city_data_dict = {
        'AREA_CONGEST_LVL': [],
        'AREA_CONGEST_MSG': [],
        'AREA_PPLTN_MIN': [],
        'AREA_PPLTN_MAX': [],
        'MALE_PPLTN_RATE': [],
        'FEMALE_PPLTN_RATE': [],
        'PPLTN_RATE_0': [],
        'PPLTN_RATE_10': [],
        'PPLTN_RATE_20': [],
        'PPLTN_RATE_30': [],
        'PPLTN_RATE_40': [],
        'PPLTN_RATE_50': [],
        'PPLTN_RATE_60': [],
        'PPLTN_RATE_70': [],
        'RESNT_PPLTN_RATE': [],
        'NON_RESNT_PPLTN_RATE': [],
        'REPLACE_YN': [],
        'PPLTN_TIME': [],
        'FCST_YN': []
    }
    
    # 데이터 추출 및 딕셔너리에 추가
    city_data_dict['AREA_CONGEST_LVL'].append(city_data['AREA_CONGEST_LVL'])
    city_data_dict['AREA_CONGEST_MSG'].append(city_data['AREA_CONGEST_MSG'])
    city_data_dict['AREA_PPLTN_MIN'].append(city_data['AREA_PPLTN_MIN'])
    city_data_dict['AREA_PPLTN_MAX'].append(city_data['AREA_PPLTN_MAX'])
    city_data_dict['MALE_PPLTN_RATE'].append(city_data['MALE_PPLTN_RATE'])
    city_data_dict['FEMALE_PPLTN_RATE'].append(city_data['FEMALE_PPLTN_RATE'])
    city_data_dict['PPLTN_RATE_0'].append(city_data['PPLTN_RATE_0'])
    city_data_dict['PPLTN_RATE_10'].append(city_data['PPLTN_RATE_10'])
    city_data_dict['PPLTN_RATE_20'].append(city_data['PPLTN_RATE_20'])
    city_data_dict['PPLTN_RATE_30'].append(city_data['PPLTN_RATE_30'])
    city_data_dict['PPLTN_RATE_40'].append(city_data['PPLTN_RATE_40'])
    city_data_dict['PPLTN_RATE_50'].append(city_data['PPLTN_RATE_50'])
    city_data_dict['PPLTN_RATE_60'].append(city_data['PPLTN_RATE_60'])
    city_data_dict['PPLTN_RATE_70'].append(city_data['PPLTN_RATE_70'])
    city_data_dict['RESNT_PPLTN_RATE'].append(city_data['RESNT_PPLTN_RATE'])
    city_data_dict['NON_RESNT_PPLTN_RATE'].append(city_data['NON_RESNT_PPLTN_RATE'])
    city_data_dict['REPLACE_YN'].append(city_data['REPLACE_YN'])
    city_data_dict['PPLTN_TIME'].append(city_data['PPLTN_TIME'])
    city_data_dict['FCST_YN'].append(city_data['FCST_YN'])
    
    # DataFrame 생성
    data1 = pd.DataFrame(city_data_dict)
    
    # DataFrame 정보 출력
    data1.info()
else:
    print("Error:", response.status_code)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   AREA_CONGEST_LVL      1 non-null      object
 1   AREA_CONGEST_MSG      1 non-null      object
 2   AREA_PPLTN_MIN        1 non-null      object
 3   AREA_PPLTN_MAX        1 non-null      object
 4   MALE_PPLTN_RATE       1 non-null      object
 5   FEMALE_PPLTN_RATE     1 non-null      object
 6   PPLTN_RATE_0          1 non-null      object
 7   PPLTN_RATE_10         1 non-null      object
 8   PPLTN_RATE_20         1 non-null      object
 9   PPLTN_RATE_30         1 non-null      object
 10  PPLTN_RATE_40         1 non-null      object
 11  PPLTN_RATE_50         1 non-null      object
 12  PPLTN_RATE_60         1 non-null      object
 13  PPLTN_RATE_70         1 non-null      object
 14  RESNT_PPLTN_RATE      1 non-null      object
 15  NON_RESNT_PPLTN_RATE  1 non-null      object
 16  REPLACE_YN            1 non-null      object
 17  PPLTN_TIME            1 non-null      object
 18  FCST_YN               1 non-null      object
dtypes: object(19)
memory usage: 280.0+ bytes

In [11]:
data1

,AREA_CONGEST_LVL,AREA_CONGEST_MSG,AREA_PPLTN_MIN,AREA_PPLTN_MAX,MALE_PPLTN_RATE,FEMALE_PPLTN_RATE,PPLTN_RATE_0,PPLTN_RATE_10,PPLTN_RATE_20,PPLTN_RATE_30,PPLTN_RATE_40,PPLTN_RATE_50,PPLTN_RATE_60,PPLTN_RATE_70,RESNT_PPLTN_RATE,NON_RESNT_PPLTN_RATE,REPLACE_YN,PPLTN_TIME,FCST_YN
0,약간 붐빔,사람들이 몰려있을 가능성이 크고 붐빈다고 느낄 수 있어요. 인구밀도가 높은 구간에서...,22000,24000,52.3,47.7,0.0,2.5,24.2,34.9,23.8,10.2,3.2,1.1,29.1,70.9,N,2023-08-24 10:05,Y

- 지명 코드

In [9]:
result = []
for num in range(1, 114):
    place = 'POI' + f'{num:03}'  # 숫자를 세 자리로 포맷팅하여 문자열 생성
    result.append(place)

print(result)  # 결과 출력

['POI001', 'POI002', 'POI003', 'POI004', 'POI005', 'POI006', 'POI007', 'POI008', 'POI009', 'POI010', 'POI011', 'POI012', 'POI013', 'POI014', 'POI015', 'POI016', 'POI017', 'POI018', 'POI019', 'POI020', 'POI021', 'POI022', 'POI023', 'POI024', 'POI025', 'POI026', 'POI027', 'POI028', 'POI029', 'POI030', 'POI031', 'POI032', 'POI033', 'POI034', 'POI035', 'POI036', 'POI037', 'POI038', 'POI039', 'POI040', 'POI041', 'POI042', 'POI043', 'POI044', 'POI045', 'POI046', 'POI047', 'POI048', 'POI049', 'POI050', 'POI051', 'POI052', 'POI053', 'POI054', 'POI055', 'POI056', 'POI057', 'POI058', 'POI059', 'POI060', 'POI061', 'POI062', 'POI063', 'POI064', 'POI065', 'POI066', 'POI067', 'POI068', 'POI069', 'POI070', 'POI071', 'POI072', 'POI073', 'POI074', 'POI075', 'POI076', 'POI077', 'POI078', 'POI079', 'POI080', 'POI081', 'POI082', 'POI083', 'POI084', 'POI085', 'POI086', 'POI087', 'POI088', 'POI089', 'POI090', 'POI091', 'POI092', 'POI093', 'POI094', 'POI095', 'POI096', 'POI097', 'POI098', 'POI099', 'POI100', 'POI101', 'POI102', 'POI103', 'POI104', 'POI105', 'POI106', 'POI107', 'POI108', 'POI109', 'POI110', 'POI111', 'POI112', 'POI113']

In [12]:
weather_df = data['SeoulRtd.citydata']['CITYDATA']['WEATHER_STTS']['WEATHER_STTS'].keys()
weather_df

dict_keys(['WEATHER_TIME', 'TEMP', 'SENSIBLE_TEMP', 'MAX_TEMP', 'MIN_TEMP', 'HUMIDITY', 'WIND_DIRCT', 'WIND_SPD', 'PRECIPITATION', 'PRECPT_TYPE', 'PCP_MSG', 'SUNRISE', 'SUNSET', 'UV_INDEX_LVL', 'UV_INDEX', 'UV_MSG', 'PM25_INDEX', 'PM25', 'PM10_INDEX', 'PM10', 'AIR_IDX', 'AIR_IDX_MVL', 'AIR_IDX_MAIN', 'AIR_MSG', 'FCST24HOURS', 'NEWS_LIST'])

In [17]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import xml.etree.ElementTree as ET

result = []
for num in range(1, 114):
    place = 'POI' + f'{num:03}'  # 숫자를 세 자리로 포맷팅하여 문자열 생성
    result.append(place)

# print(result)  # 결과 출력

for p in result:
    url = "http://openapi.seoul.go.kr:8088/69576567536c736f3133357542784147/xml/citydata/1/5/"+str(p)
    req = requests.get(url)

soup = BeautifulSoup(req.content, "html.parser")

if req.status_code == 200:
    data = xmltodict.parse(req.text)
    
    # 실제 데이터가 있는 키 확인 및 사용
    city_data = data['SeoulRtd.citydata']['CITYDATA']['WEATHER_STTS']['WEATHER_STTS']
    
    # DataFrame 생성을 위한 딕셔너리 초기화
    city_data_dict = {
        'WEATHER_TIME': [],
        'TEMP': [],
        'SENSIBLE_TEMP': [],
        'MAX_TEMP': [],
        'MIN_TEMP': [],
        'HUMIDITY': [],
        'WIND_DIRCT': [],
        'WIND_SPD': [],
        'PRECIPITATION': [],
        'PRECPT_TYPE': [],
        'PCP_MSG': []
    }
    
    # 데이터 추출 및 딕셔너리에 추가
    city_data_dict['WEATHER_TIME'].append(city_data['WEATHER_TIME'])
    city_data_dict['TEMP'].append(city_data['TEMP'])
    city_data_dict['SENSIBLE_TEMP'].append(city_data['SENSIBLE_TEMP'])
    city_data_dict['MAX_TEMP'].append(city_data['MAX_TEMP'])
    city_data_dict['MIN_TEMP'].append(city_data['MIN_TEMP'])
    city_data_dict['HUMIDITY'].append(city_data['HUMIDITY'])
    city_data_dict['WIND_DIRCT'].append(city_data['WIND_DIRCT'])
    city_data_dict['WIND_SPD'].append(city_data['WIND_SPD'])
    city_data_dict['PRECIPITATION'].append(city_data['PRECIPITATION'])
    city_data_dict['PRECPT_TYPE'].append(city_data['PRECPT_TYPE'])
    city_data_dict['PCP_MSG'].append(city_data['PCP_MSG'])
    
    # DataFrame 생성
    data1 = pd.DataFrame(city_data_dict)
    
    # DataFrame 정보 출력
    data1.info()
else:
    print("Error:", req.status_code)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   WEATHER_TIME   1 non-null      object
 1   TEMP           1 non-null      object
 2   SENSIBLE_TEMP  1 non-null      object
 3   MAX_TEMP       1 non-null      object
 4   MIN_TEMP       1 non-null      object
 5   HUMIDITY       1 non-null      object
 6   WIND_DIRCT     1 non-null      object
 7   WIND_SPD       1 non-null      object
 8   PRECIPITATION  1 non-null      object
 9   PRECPT_TYPE    1 non-null      object
 10  PCP_MSG        1 non-null      object
dtypes: object(11)
memory usage: 216.0+ bytes

In [18]:
data1

,WEATHER_TIME,TEMP,SENSIBLE_TEMP,MAX_TEMP,MIN_TEMP,HUMIDITY,WIND_DIRCT,WIND_SPD,PRECIPITATION,PRECPT_TYPE,PCP_MSG
0,2023-08-24 16:12,27.5,29.3,30,25,77,NNE,3.2,-,없음,비 또는 눈 소식이 없어요.