In [13]:
## 공공데이터포털: 한국교통안전공단_대중교통 기상상태별 이용인원
### 8/31 데이터 업데이트 된다고 함
import requests

url= "https://api.odcloud.kr/api/15074244/v1/uddi:d4b76ee2-5d28-422f-8d28-eaf507093a05?page=1&perPage=20&serviceKey=mKYxnFwhEBI%2FOjbWv9%2Bisjkcglnr9q51ME7y21XvYuG5PbS54UoeDwQF9tdSk1ytoJ7lhYAC3cD7gsmnks8mAw%3D%3D"
req = requests.get(url)
print(req)

<Response [200]>

In [31]:
json_df = req.json()
json_df

{'currentCount': 17,
 'data': [{'강설': '2,956,729',
   '강우': '3,376,563',
   '구분1': '서울',
   '맑은 날': '3,493,041'},
  {'강설': '628,552', '강우': '761,675', '구분1': '부산', '맑은 날': '827,043'},
  {'강설': '354,555', '강우': '374,781', '구분1': '대구', '맑은 날': '398,102'},
  {'강설': '497,790', '강우': '549,433', '구분1': '인천', '맑은 날': '582,456'},
  {'강설': '165,855', '강우': '153,363', '구분1': '광주', '맑은 날': '164,801'},
  {'강설': '190,589', '강우': '177,120', '구분1': '대전', '맑은 날': '192,403'},
  {'강설': '76,561', '강우': '99,450', '구분1': '울산', '맑은 날': '103,108'},
  {'강설': '24,249', '강우': '25,122', '구분1': '세종', '맑은 날': '26,623'},
  {'강설': '2,006,961', '강우': '2,234,957', '구분1': '경기', '맑은 날': '2,339,021'},
  {'강설': '47,599', '강우': '47,988', '구분1': '강원', '맑은 날': '66,742'},
  {'강설': '58,740', '강우': '72,257', '구분1': '충북', '맑은 날': '76,629'},
  {'강설': '95,328', '강우': '114,189', '구분1': '충남', '맑은 날': '121,206'},
  {'강설': '70,382', '강우': '78,762', '구분1': '전북', '맑은 날': '87,534'},
  {'강설': '81,597', '강우': '89,609', '구분1': '전남', '맑은 날': '102,009'},
  {'강설': '95,111', '강우': '97,891', '구분1': '경북', '맑은 날': '103,193'},
  {'강설': '206,873', '강우': '235,082', '구분1': '경남', '맑은 날': '240,703'},
  {'강설': '66,518', '강우': '65,258', '구분1': '제주', '맑은 날': '78,443'}],
 'matchCount': 17,
 'page': 1,
 'perPage': 20,
 'totalCount': 17}

In [32]:
import pandas as pd

df = pd.DataFrame(json_df)
print(df)

    currentCount                                               data  \
0             17  {'강설': '2,956,729', '강우': '3,376,563', '구분1': ...
1             17  {'강설': '628,552', '강우': '761,675', '구분1': '부산'...
2             17  {'강설': '354,555', '강우': '374,781', '구분1': '대구'...
3             17  {'강설': '497,790', '강우': '549,433', '구분1': '인천'...
4             17  {'강설': '165,855', '강우': '153,363', '구분1': '광주'...
5             17  {'강설': '190,589', '강우': '177,120', '구분1': '대전'...
6             17  {'강설': '76,561', '강우': '99,450', '구분1': '울산', ...
7             17  {'강설': '24,249', '강우': '25,122', '구분1': '세종', ...
8             17  {'강설': '2,006,961', '강우': '2,234,957', '구분1': ...
9             17  {'강설': '47,599', '강우': '47,988', '구분1': '강원', ...
10            17  {'강설': '58,740', '강우': '72,257', '구분1': '충북', ...
11            17  {'강설': '95,328', '강우': '114,189', '구분1': '충남',...
12            17  {'강설': '70,382', '강우': '78,762', '구분1': '전북', ...
13            17  {'강설': '81,597', '강우': '89,609', '구분1': '전남', ...
14            17  {'강설': '95,111', '강우': '97,891', '구분1': '경북', ...
15            17  {'강설': '206,873', '강우': '235,082', '구분1': '경남'...
16            17  {'강설': '66,518', '강우': '65,258', '구분1': '제주', ...

    matchCount  page  perPage  totalCount
0           17     1       20          17
1           17     1       20          17
2           17     1       20          17
3           17     1       20          17
4           17     1       20          17
5           17     1       20          17
6           17     1       20          17
7           17     1       20          17
8           17     1       20          17
9           17     1       20          17
10          17     1       20          17
11          17     1       20          17
12          17     1       20          17
13          17     1       20          17
14          17     1       20          17
15          17     1       20          17
16          17     1       20          17

In [33]:
df.columns

Index(['currentCount', 'data', 'matchCount', 'page', 'perPage', 'totalCount'], dtype='object')

In [34]:
df['data'].values

array([{'강설': '2,956,729', '강우': '3,376,563', '구분1': '서울', '맑은 날': '3,493,041'},
       {'강설': '628,552', '강우': '761,675', '구분1': '부산', '맑은 날': '827,043'},
       {'강설': '354,555', '강우': '374,781', '구분1': '대구', '맑은 날': '398,102'},
       {'강설': '497,790', '강우': '549,433', '구분1': '인천', '맑은 날': '582,456'},
       {'강설': '165,855', '강우': '153,363', '구분1': '광주', '맑은 날': '164,801'},
       {'강설': '190,589', '강우': '177,120', '구분1': '대전', '맑은 날': '192,403'},
       {'강설': '76,561', '강우': '99,450', '구분1': '울산', '맑은 날': '103,108'},
       {'강설': '24,249', '강우': '25,122', '구분1': '세종', '맑은 날': '26,623'},
       {'강설': '2,006,961', '강우': '2,234,957', '구분1': '경기', '맑은 날': '2,339,021'},
       {'강설': '47,599', '강우': '47,988', '구분1': '강원', '맑은 날': '66,742'},
       {'강설': '58,740', '강우': '72,257', '구분1': '충북', '맑은 날': '76,629'},
       {'강설': '95,328', '강우': '114,189', '구분1': '충남', '맑은 날': '121,206'},
       {'강설': '70,382', '강우': '78,762', '구분1': '전북', '맑은 날': '87,534'},
       {'강설': '81,597', '강우': '89,609', '구분1': '전남', '맑은 날': '102,009'},
       {'강설': '95,111', '강우': '97,891', '구분1': '경북', '맑은 날': '103,193'},
       {'강설': '206,873', '강우': '235,082', '구분1': '경남', '맑은 날': '240,703'},
       {'강설': '66,518', '강우': '65,258', '구분1': '제주', '맑은 날': '78,443'}],
      dtype=object)

In [37]:
type(df1)

dict

In [39]:
df2 = pd.Series(df1)
df2

강설      2,956,729
강우      3,376,563
구분1            서울
맑은 날    3,493,041
dtype: object

In [43]:
df2['해당연도'] = 20211231
df2

강설      2,956,729
강우      3,376,563
구분1            서울
맑은 날    3,493,041
해당연도     20211231
dtype: object