In [1]:
import requests

url = "http://openapi.seoul.go.kr:8088/4e504750706c736f39374252465a73/json/tbLnOpendataRtmsV/1/5/"
req = requests.get(url)
print(req)

<Response [200]>

In [2]:
json_df = req.json()
json_df

{'tbLnOpendataRtmsV': {'list_total_count': 2677272,
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'ACC_YEAR': '2023',
    'SGG_CD': '11710',
    'SGG_NM': '송파구',
    'BJDONG_CD': '10800',
    'BJDONG_NM': '문정동',
    'LAND_GBN': '1',
    'LAND_GBN_NM': '대지',
    'BONBEON': '0652',
    'BUBEON': '0004',
    'BLDG_NM': '힐스테이트에코문정',
    'DEAL_YMD': '20230805',
    'OBJ_AMT': '20500',
    'BLDG_AREA': 20.79,
    'TOT_AREA': 32.68,
    'FLOOR': 4.0,
    'RIGHT_GBN': '',
    'CNTL_YMD': '',
    'BUILD_YEAR': '2018',
    'HOUSE_TYPE': '오피스텔',
    'REQ_GBN': '중개거래',
    'RDEALER_LAWDNM': '서울 송파구'},
   {'ACC_YEAR': '2023',
    'SGG_CD': '11560',
    'SGG_NM': '영등포구',
    'BJDONG_CD': '10900',
    'BJDONG_NM': '영등포동8가',
    'LAND_GBN': '1',
    'LAND_GBN_NM': '대지',
    'BONBEON': '0051',
    'BUBEON': '0001',
    'BLDG_NM': '메이준',
    'DEAL_YMD': '20230804',
    'OBJ_AMT': '8000',
    'BLDG_AREA': 17.44,
    'TOT_AREA': 25.56,
    'FLOOR': 6.0,
    'RIGHT_GBN': '',
    'CNTL_YMD': '',
    'BUILD_YEAR': '2012',
    'HOUSE_TYPE': '오피스텔',
    'REQ_GBN': '중개거래',
    'RDEALER_LAWDNM': '서울 영등포구'},
   {'ACC_YEAR': '2023',
    'SGG_CD': '11380',
    'SGG_NM': '은평구',
    'BJDONG_CD': '10500',
    'BJDONG_NM': '구산동',
    'LAND_GBN': '1',
    'LAND_GBN_NM': '대지',
    'BONBEON': '0345',
    'BUBEON': '0020',
    'BLDG_NM': '솔빛엘르빌',
    'DEAL_YMD': '20230804',
    'OBJ_AMT': '22000',
    'BLDG_AREA': 49.3,
    'TOT_AREA': 27.73,
    'FLOOR': 2.0,
    'RIGHT_GBN': '',
    'CNTL_YMD': '',
    'BUILD_YEAR': '2012',
    'HOUSE_TYPE': '연립다세대',
    'REQ_GBN': '중개거래',
    'RDEALER_LAWDNM': '서울 은평구'},
   {'ACC_YEAR': '2023',
    'SGG_CD': '11620',
    'SGG_NM': '관악구',
    'BJDONG_CD': '10100',
    'BJDONG_NM': '봉천동',
    'LAND_GBN': '1',
    'LAND_GBN_NM': '대지',
    'BONBEON': '1708',
    'BUBEON': '0000',
    'BLDG_NM': '두산',
    'DEAL_YMD': '20230804',
    'OBJ_AMT': '80000',
    'BLDG_AREA': 59.92,
    'TOT_AREA': 0.0,
    'FLOOR': 10.0,
    'RIGHT_GBN': '',
    'CNTL_YMD': '',
    'BUILD_YEAR': '2000',
    'HOUSE_TYPE': '아파트',
    'REQ_GBN': '중개거래',
    'RDEALER_LAWDNM': '서울 관악구'},
   {'ACC_YEAR': '2023',
    'SGG_CD': '11500',
    'SGG_NM': '강서구',
    'BJDONG_CD': '10300',
    'BJDONG_NM': '화곡동',
    'LAND_GBN': '1',
    'LAND_GBN_NM': '대지',
    'BONBEON': '1071',
    'BUBEON': '0007',
    'BLDG_NM': '와이앤비',
    'DEAL_YMD': '20230804',
    'OBJ_AMT': '22500',
    'BLDG_AREA': 25.38,
    'TOT_AREA': 15.19,
    'FLOOR': 3.0,
    'RIGHT_GBN': '',
    'CNTL_YMD': '',
    'BUILD_YEAR': '2017',
    'HOUSE_TYPE': '연립다세대',
    'REQ_GBN': '중개거래',
    'RDEALER_LAWDNM': '서울 강서구'}]}}

In [4]:
import pandas as pd

houses = json_df['tbLnOpendataRtmsV']['row']
data_1 = pd.DataFrame(houses)
print(data_1)

  ACC_YEAR SGG_CD SGG_NM BJDONG_CD BJDONG_NM LAND_GBN LAND_GBN_NM BONBEON  \
0     2023  11710    송파구     10800       문정동        1          대지    0652
1     2023  11560   영등포구     10900    영등포동8가        1          대지    0051
2     2023  11380    은평구     10500       구산동        1          대지    0345
3     2023  11620    관악구     10100       봉천동        1          대지    1708
4     2023  11500    강서구     10300       화곡동        1          대지    1071

  BUBEON    BLDG_NM  ... OBJ_AMT BLDG_AREA  TOT_AREA  FLOOR  RIGHT_GBN  \
0   0004  힐스테이트에코문정  ...   20500     20.79     32.68    4.0
1   0001        메이준  ...    8000     17.44     25.56    6.0
2   0020      솔빛엘르빌  ...   22000     49.30     27.73    2.0
3   0000         두산  ...   80000     59.92      0.00   10.0
4   0007       와이앤비  ...   22500     25.38     15.19    3.0

  CNTL_YMD BUILD_YEAR HOUSE_TYPE REQ_GBN RDEALER_LAWDNM
0                2018       오피스텔    중개거래         서울 송파구
1                2012       오피스텔    중개거래        서울 영등포구
2                2012      연립다세대    중개거래         서울 은평구
3                2000        아파트    중개거래         서울 관악구
4                2017      연립다세대    중개거래         서울 강서구

[5 rows x 21 columns]

In [20]:
import requests
import lxml
from bs4 import BeautifulSoup

url = "http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev?serviceKey=mKYxnFwhEBI%2FOjbWv9%2Bisjkcglnr9q51ME7y21XvYuG5PbS54UoeDwQF9tdSk1ytoJ7lhYAC3cD7gsmnks8mAw%3D%3D&pageNo=1&numOfRows=10&LAWD_CD=11110&DEAL_YMD=202305"
req = requests.get(url)
# print(req.text)

soup = BeautifulSoup(req.text, "lxml") # XML 반환값이라서 lxml을 사용한 것
# print(soup.prettify())

# # xml결과값으로 데이터프레임 변환
거래금액_list = soup.find_all("거래금액")
건축년도_list = soup.find_all("건축년도")

거래금액 = []
건축년도 = []
for price, type in zip(거래금액_list, 거래유형_list):
    print(price.get_text(), type.get_text())
    거래금액.append(price.get_text())
    건축년도.append(type.get_text())

df = pd.DataFrame({"price":거래금액, "type" : 건축년도})
df

Empty DataFrame
Columns: [price, type]
Index: []

In [ ]:
# 공공데이터포털

In [29]:
import requests
import pandas as pd 

serviceKey = 'mKYxnFwhEBI%2FOjbWv9%2Bisjkcglnr9q51ME7y21XvYuG5PbS54UoeDwQF9tdSk1ytoJ7lhYAC3cD7gsmnks8mAw%3D%3D'
pageNo = 1 # 페이지 번호
numOfRows = 1000 # 한 페이지 결과수
LAWD_CD = 11560 # 지역코드
DEAL_YMD = 202307 # 계약월
url = f'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev?serviceKey={serviceKey}&pageNo={pageNo}&numOfRows=10&LAWD_CD={LAWD_CD}&DEAL_YMD={DEAL_YMD}'
req = requests.get(url)
req.text

'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><header><resultCode>00</resultCode><resultMsg>NORMAL SERVICE.</resultMsg></header><body><items><item><거래금액>    41,700</거래금액><거래유형>중개거래</거래유형><건축년도>2020</건축년도><년>2023</년><도로명>경인로</도로명><도로명건물본번호코드>00900</도로명건물본번호코드><도로명건물부번호코드>00000</도로명건물부번호코드><도로명시군구코드>11560</도로명시군구코드><도로명일련번호코드>00</도로명일련번호코드><도로명코드>3000028</도로명코드><등기일자> </등기일자><법정동> 영등포동1가</법정동><법정동본번코드>0094</법정동본번코드><법정동부번코드>0002</법정동부번코드><법정동시군구코드>11560</법정동시군구코드><법정동읍면동코드>10200</법정동읍면동코드><법정동지번코드>1</법정동지번코드><아파트>여의도더리브스타일</아파트><월>7</월><일>1</일><일련번호>11560-2153</일련번호><전용면적>30.2696</전용면적><중개사소재지>서울 영등포구</중개사소재지><지번>94-2</지번><지역코드>11560</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    30,500</거래금액><거래유형>직거래</거래유형><건축년도>2022</건축년도><년>2023</년><도로명>경인로114길</도로명><도로명건물본번호코드>00006</도로명건물본번호코드><도로명건물부번호코드>00000</도로명건물부번호코드><도로명시군구코드>11560</도로명시군구코드><도로명일련번호코드>00</도로명일련번호코드><도로명지상지하코드>0</도로명지상지하코드><도로명코드>4154044</도로명코드><등기일자>23.08.01</등기일자><법정동> 영등포동1가</법정동><법정동본번코드>0092</법정동본번코드><법정동부번코드>0003</법정동부번코드><법정동시군구코드>11560</법정동시군구코드><법정동읍면동코드>10200</법정동읍면동코드><법정동지번코드>1</법정동지번코드><아파트>여의도이튼브라운</아파트><월>7</월><일>31</일><일련번호>11560-2281</일련번호><전용면적>31.19</전용면적><중개사소재지> </중개사소재지><지번>92-3</지번><지역코드>11560</지역코드><층>5</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    62,260</거래금액><거래유형>중개거래</거래유형><건축년도>2022</건축년도><년>2023</년><도로명>버드나루로</도로명><도로명건물본번호코드>00005</도로명건물본번호코드><도로명건물부번호코드>00000</도로명건물부번호코드><도로명시군구코드>11560</도로명시군구코드><도로명일련번호코드>00</도로명일련번호코드><도로명지상지하코드>0</도로명지상지하코드><도로명코드>3118010</도로명코드><등기일자> </등기일자><법정동> 영등포동2가</법정동><법정동본번코드>0139</법정동본번코드><법정동부번코드>0000</법정동부번코드><법정동시군구코드>11560</법정동시군구코드><법정동읍면동코드>10300</법정동읍면동코드><법정동지번코드>1</법정동지번코드><아파트>여의도리미티오148</아파트><월>7</월><일>17</일><일련번호>11560-2270</일련번호><전용면적>38.441</전용면적><중개사소재지>서울 영등포구</중개사소재지><지번>139</지번><지역코드>11560</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    62,260</거래금액><거래유형>중개거래</거래유형><건축년도>2022</건축년도><년>2023</년><도로명>버드나루로</도로명><도로명건물본번호코드>00005</도로명건물본번호코드><도로명건물부번호코드>00000</도로명건물부번호코드><도로명시군구코드>11560</도로명시군구코드><도로명일련번호코드>00</도로명일련번호코드><도로명지상지하코드>0</도로명지상지하코드><도로명코드>3118010</도로명코드><등기일자> </등기일자><법정동> 영등포동2가</법정동><법정동본번코드>0139</법정동본번코드><법정동부번코드>0000</법정동부번코드><법정동시군구코드>11560</법정동시군구코드><법정동읍면동코드>10300</법정동읍면동코드><법정동지번코드>1</법정동지번코드><아파트>여의도리미티오148</아파트><월>7</월><일>17</일><일련번호>11560-2270</일련번호><전용면적>38.441</전용면적><중개사소재지>서울 영등포구</중개사소재지><지번>139</지번><지역코드>11560</지역코드><층>8</층><해제사유발생일>23.08.01</해제사유발생일><해제여부>O</해제여부></item><item><거래금액>    10,400</거래금액><거래유형>중개거래</거래유형><건축년도>2014</건축년도><년>2023</년><도로명>영중로6길</도로명><도로명건물본번호코드>00012</도로명건물본번호코드><도로명건물부번호코드>00000</도로명건물부번호코드><도로명시군구코드>11560</도로명시군구코드><도로명일련번호코드>01</도로명일련번호코드><도로명지상지하코드>0</도로명지상지하코드><도로명코드>4154816</도로명코드><등기일자> </등기일자><법정동> 영등포동3가</법정동><법정동본번코드>0019</법정동본번코드><법정동부번코드>0002</법정동부번코드><법정동시군구코드>11560</법정동시군구코드><법정동읍면동코드>10400</법정동읍면동코드><법정동지번코드>1</법정동지번코드><아파트>포레스트힐시티</아파트><월>7</월><일>7</일><일련번호>11560-1680</일련번호><전용면적>13.53</전용면적><중개사소재지>서울 영등포구</중개사소재지><지번>19-2</지번><지역코드>11560</지역코드><층>7</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   145,700</거래금액><거래유형>중개거래</거래유형><건축년도>2017</건축년도><년>2023</년><도로명>국회대로54길</도로명><도로명건물본번호코드>00010</도로명건물본번호코드><도로명건물부번호코드>00000</도로명건물부번호코드><도로명시군구코드>11560</도로명시군구코드><도로명일련번호코드>00</도로명일련번호코드><도로명코드>4154084</도로명코드><등기일자> </등기일자><법정동> 영등포동7가</법정동><법정동본번코드>0203</법정동본번코드><법정동부번코드>0000</법정동부번코드><법정동시군구코드>11560</법정동시군구코드><법정동읍면동코드>10800</법정동읍면동코드><법정동지번코드>1</법정동지번코드><아파트>아크로타워스퀘어</아파트><월>7</월><일>4</일><일련번호>11560-1955</일련번호><전용면적>84.75</전용면적><중개사소재지>서울 영등포구</중개사소재지><지번>203</지번><지역코드>11560</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   145,000</거래금액><거래유형>중개거래</거래유형><건축년도>2017</건축년도><년>2023</년><도로명>국회대로54길</도로명><도로명건물본번호코드>00010</도로명건물본번호코드><도로명건물부번호코드>00000</도로명건물부번호코드><도로명시군구코드>11560</도로명시군구코드><도로명일련번호코드>00</도로명일련번호코드><도로명코드>4154084</도로명코드><등기일자> </등기일자><법정동> 영등포동7가</법정동><법정동본번코드>0203</법정동본번코드><법정동부번코드>0000</법정동부번코드><법정동시군구코드>11560</법정동시군구코드><법정동읍면동코드>10800</법정동읍면동코드><법정동지번코드>1</법정동지번코드><아파트>아크로타워스퀘어</아파트><월>7</월><일>6</일><일련번호>11560-1955</일련번호><전용면적>84.75</전용면적><중개사소재지>서울 영등포구</중개사소재지><지번>203</지번><지역코드>11560</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   120,000</거래금액><거래유형>중개거래</거래유형><건축년도>2017</건축년도><년>2023</년><도로명>국회대로54길</도로명><도로명건물본번호코드>00010</도로명건물본번호코드><도로명건물부번호코드>00000</도로명건물부번호코드><도로명시군구코드>11560</도로명시군구코드><도로명일련번호코드>00</도로명일련번호코드><도로명코드>4154084</도로명코드><등기일자> </등기일자><법정동> 영등포동7가</법정동><법정동본번코드>0203</법정동본번코드><법정동부번코드>0000</법정동부번코드><법정동시군구코드>11560</법정동시군구코드><법정동읍면동코드>10800</법정동읍면동코드><법정동지번코드>1</법정동지번코드><아파트>아크로타워스퀘어</아파트><월>7</월><일>6</일><일련번호>11560-1955</일련번호><전용면적>59.91</전용면적><중개사소재지>서울 송파구, 서울 영등포구</중개사소재지><지번>203</지번><지역코드>11560</지역코드><층>13</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    81,000</거래금액><거래유형>중개거래</거래유형><건축년도>1999</건축년도><년>2023</년><도로명>영중로</도로명><도로명건물본번호코드>00145</도로명건물본번호코드><도로명건물부번호코드>00000</도로명건물부번호코드><도로명시군구코드>11560</도로명시군구코드><도로명일련번호코드>06</도로명일련번호코드><도로명지상지하코드>0</도로명지상지하코드><도로명코드>3118024</도로명코드><등기일자> </등기일자><법정동> 영등포동8가</법정동><법정동본번코드>0076</법정동본번코드><법정동부번코드>0001</법정동부번코드><법정동시군구코드>11560</법정동시군구코드><법정동읍면동코드>10900</법정동읍면동코드><법정동지번코드>1</법정동지번코드><아파트>삼환</아파트><월>7</월><일>1</일><일련번호>11560-7</일련번호><전용면적>59.91</전용면적><중개사소재지>서울 영등포구</중개사소재지><지번>76-1</지번><지역코드>11560</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   102,000</거래금액><거래유형>중개거래</거래유형><건축년도>1999</건축년도><년>2023</년><도로명>영중로</도로명><도로명건물본번호코드>00145</도로명건물본번호코드><도로명건물부번호코드>00000</도로명건물부번호코드><도로명시군구코드>11560</도로명시군구코드><도로명일련번호코드>06</도로명일련번호코드><도로명지상지하코드>0</도로명지상지하코드><도로명코드>3118024</도로명코드><등기일자> </등기일자><법정동> 영등포동8가</법정동><법정동본번코드>0076</법정동본번코드><법정동부번코드>0001</법정동부번코드><법정동시군구코드>11560</법정동시군구코드><법정동읍면동코드>10900</법정동읍면동코드><법정동지번코드>1</법정동지번코드><아파트>삼환</아파트><월>7</월><일>4</일><일련번호>11560-7</일련번호><전용면적>84.87</전용면적><중개사소재지>서울 양천구, 서울 영등포구</중개사소재지><지번>76-1</지번><지역코드>11560</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item></items><numOfRows>10</numOfRows><pageNo>1</pageNo><totalCount>118</totalCount></body></response>'

In [28]:
!pip install xmltodict

Requirement already satisfied: xmltodict in c:\users\user\desktop\tempproject\venv\lib\site-packages (0.13.0)

In [32]:
import xmltodict
import pandas as pd

data_dict = xmltodict.parse(req.text)
# data_dict
pd.DataFrame(data_dict['response']['body']['items']['item'])

,거래금액,거래유형,건축년도,년,도로명,도로명건물본번호코드,도로명건물부번호코드,도로명시군구코드,도로명일련번호코드,도로명코드,...,일,일련번호,전용면적,중개사소재지,지번,지역코드,층,해제사유발생일,해제여부,도로명지상지하코드
0,"41,700",중개거래,2020,2023,경인로,00900,00000,11560,00,3000028,...,1,11560-2153,30.2696,서울 영등포구,94-2,11560,3,None,None,NaN
1,"30,500",직거래,2022,2023,경인로114길,00006,00000,11560,00,4154044,...,31,11560-2281,31.19,None,92-3,11560,5,None,None,0
2,"62,260",중개거래,2022,2023,버드나루로,00005,00000,11560,00,3118010,...,17,11560-2270,38.441,서울 영등포구,139,11560,8,None,None,0
3,"62,260",중개거래,2022,2023,버드나루로,00005,00000,11560,00,3118010,...,17,11560-2270,38.441,서울 영등포구,139,11560,8,23.08.01,O,0
4,"10,400",중개거래,2014,2023,영중로6길,00012,00000,11560,01,4154816,...,7,11560-1680,13.53,서울 영등포구,19-2,11560,7,None,None,0
5,"145,700",중개거래,2017,2023,국회대로54길,00010,00000,11560,00,4154084,...,4,11560-1955,84.75,서울 영등포구,203,11560,12,None,None,NaN
6,"145,000",중개거래,2017,2023,국회대로54길,00010,00000,11560,00,4154084,...,6,11560-1955,84.75,서울 영등포구,203,11560,11,None,None,NaN
7,"120,000",중개거래,2017,2023,국회대로54길,00010,00000,11560,00,4154084,...,6,11560-1955,59.91,"서울 송파구, 서울 영등포구",203,11560,13,None,None,NaN
8,"81,000",중개거래,1999,2023,영중로,00145,00000,11560,06,3118024,...,1,11560-7,59.91,서울 영등포구,76-1,11560,6,None,None,0
9,"102,000",중개거래,1999,2023,영중로,00145,00000,11560,06,3118024,...,4,11560-7,84.87,"서울 양천구, 서울 영등포구",76-1,11560,6,None,None,0

In [ ]:
### 서울 열린데이터광장

In [33]:
import requests
import json
import pandas as pd
SERVICE_KEY = '564b7852646a686a34336f4f6c5571'
url = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/1/1000/2023/11560'
req = requests.get(url)
req

In [35]:
content = req.json()
result = pd.DataFrame(content['tbLnOpendataRtmsV']['row'])
result

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2023,11560,영등포구,10900,영등포동8가,1,대지,0051,0001,메이준,...,8000,17.44,25.56,6.0,,,2012,오피스텔,중개거래,서울 영등포구
1,2023,11560,영등포구,13200,신길동,1,대지,4934,0000,삼성래미안,...,75000,59.33,0.00,5.0,,,2001,아파트,중개거래,서울 영등포구
2,2023,11560,영등포구,12100,문래동3가,1,대지,0013,0000,문래해태,...,68000,84.69,0.00,13.0,,,1999,아파트,중개거래,서울 영등포구
3,2023,11560,영등포구,10300,영등포동2가,1,대지,0028,0118,그린나래,...,37500,56.51,63.16,5.0,,,2014,오피스텔,중개거래,서울 영등포구
4,2023,11560,영등포구,13300,대림동,,,,,,...,77000,216.88,111.20,0.0,,,1985,단독다가구,직거래,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,47650,46.02,27.22,2.0,,,2023,연립다세대,직거래,
996,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,47300,46.03,27.22,2.0,,,2023,연립다세대,직거래,
997,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,47950,46.03,27.22,3.0,,,2023,연립다세대,직거래,
998,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,47950,46.03,27.22,4.0,,,2023,연립다세대,직거래,
999,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,49000,46.74,27.64,3.0,,,2023,연립다세대,직거래,

In [48]:
import requests
import json
import pandas as pd
SERVICE_KEY = '564b7852646a686a34336f4f6c5571'

data = None
for j in range(1,13):
    url = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/{1+((j-1)*1000)}/{j*1000}'
    # url = f'http://openapi.seoul.go.kr:8088/{service_key}/json/tbLnOpendataRentV/1/1000/2023/11560'
    print(url)
    req = requests.get(url)
    content = req.json()
    con = content['tbLnOpendataRtmsV']['row']
    result = pd.DataFrame(con)
    data = pd.concat([data, result])
data = data.reset_index(drop=True)
data.head()

http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/1/1000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/1001/2000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/2001/3000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/3001/4000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/4001/5000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/5001/6000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/6001/7000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/7001/8000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/8001/9000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/9001/10000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/10001/11000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/11001/12000

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2023,11710,송파구,10800,문정동,1,대지,0652,0004,힐스테이트에코문정,...,20500,20.79,32.68,4.0,,,2018,오피스텔,중개거래,서울 송파구
1,2023,11560,영등포구,10900,영등포동8가,1,대지,0051,0001,메이준,...,8000,17.44,25.56,6.0,,,2012,오피스텔,중개거래,서울 영등포구
2,2023,11380,은평구,10500,구산동,1,대지,0345,0020,솔빛엘르빌,...,22000,49.30,27.73,2.0,,,2012,연립다세대,중개거래,서울 은평구
3,2023,11620,관악구,10100,봉천동,1,대지,1708,0000,두산,...,80000,59.92,0.00,10.0,,,2000,아파트,중개거래,서울 관악구
4,2023,11500,강서구,10300,화곡동,1,대지,1071,0007,와이앤비,...,22500,25.38,15.19,3.0,,,2017,연립다세대,중개거래,서울 강서구

In [52]:
data.to_csv("result.csv", index=False)